# Generated by Django 6.0.5 on 2026-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
