# Generated by Django 6.0.5 on 2026-05-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_custom2_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="personal_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
