# Generated by Django 5.0.10 on 2026-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_anime_personal_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="image_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
