# Generated by Django 6.0.5 on 2026-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=500)),
                ("category", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("synopsis", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
