# Generated by Django 6.0.5 on 2026-05-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_anime_updated_at"),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('api', 'Anime').objects.filter(
                category='Custom 2'
            ).update(category='New Anime to Watch Personal'),
            migrations.RunPython.noop,  # reverse: do nothing
        ),
    ]
