# Generated by Django 6.0.5 on 2026-05-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_anime_personal_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="personal_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
