# Generated by Django 5.0.10 on 2026-06-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_anime_image_base64"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="watched_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
